## spring.application.name=Mascota
server:
  port: 8083

spring:
  application:
    name: Mascota
  datasource:
    url: jdbc:mysql://localhost:3306/veterinaria
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect