spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      # configuracion global de CORS
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:4200"
              - "http://localhost:4201"
              - "http://127.0.0.1:4200"
              - "http://127.0.0.1:4201"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            exposed-headers: "Authorization"

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
