spring:
  application:
    name: Configuraciones
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Gimblet/DAW2-config
          force-pull: true
          default-label: main
      label: main
server:
  port: 8888